# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    networks:
      - dbnetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    networks:
      - dbnetwork

networks:
  dbnetwork: