CREATE SEQUENCE tab_usuarios_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE TAB_USUARIOS (
    USUARIO_ID integer DEFAULT nextval('tab_usuarios_seq') NOT NULL,
    LOGIN varchar(100) NOT NULL,
    SENHA varchar(255) NOT NULL,
    CONSTRAINT PK_USUARIO_ID PRIMARY KEY (USUARIO_ID)
);